### ISSUE TITLE
Three failing tests in release mode

### ISSUE THREAD

**Issue by MoSal** [RazrFalcon/ttf-parser#173]
The following tests fail with `cargo test --release`. They pass in debug mode.

```
failures:
    colr::colr1_variable::skew
    colr::colr1_variable::skew_around_center
    font_collection_num_fonts_overflow_2
```

**Comment by RazrFalcon** [comment]
For me only `font_collection_num_fonts_overflow_2` is failing. Which is by design.

What hardware do you have? Do you have a x86 CPU? 

@LaurenzV any ideas why COLR can be failing? It's fine on my M1.

**Comment by MoSal** [comment]
@RazrFalcon 

Actually, this may have been a nightly regression. Let me confirm...

**Comment by MoSal** [comment]
Yes. It was a nightly regression.
Apologies for the noise.

nightly-2024-08-29 bad
nightly-2024-08-30 good
```
failures:

---- colr::colr1_variable::skew stdout ----
thread 'colr::colr1_variable::skew' panicked at tests/tables/colr.rs:470:9:
assertion failed: vec_painter.0.contains(&Transform(ttf_parser::Transform::new_skew(0.3944702,
                0.0)))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- colr::colr1_variable::skew_around_center stdout ----
thread 'colr::colr1_variable::skew_around_center' panicked at tests/tables/colr.rs:479:9:
assertion failed: vec_painter.0.contains(&Transform(ttf_parser::Transform::new_skew(0.3944702,
                0.0)))
```
